/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessoIdRouteImport } from './routes/processo.$id'
import { Route as AdminListasRouteImport } from './routes/admin.listas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoIdRoute = ProcessoIdRouteImport.update({
  id: '/processo/$id',
  path: '/processo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListasRoute = AdminListasRouteImport.update({
  id: '/admin/listas',
  path: '/admin/listas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/listas': typeof AdminListasRoute
  '/processo/$id': typeof ProcessoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/listas': typeof AdminListasRoute
  '/processo/$id': typeof ProcessoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/listas': typeof AdminListasRoute
  '/processo/$id': typeof ProcessoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/listas' | '/processo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/listas' | '/processo/$id'
  id: '__root__' | '/' | '/admin/listas' | '/processo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminListasRoute: typeof AdminListasRoute
  ProcessoIdRoute: typeof ProcessoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/$id': {
      id: '/processo/$id'
      path: '/processo/$id'
      fullPath: '/processo/$id'
      preLoaderRoute: typeof ProcessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listas': {
      id: '/admin/listas'
      path: '/admin/listas'
      fullPath: '/admin/listas'
      preLoaderRoute: typeof AdminListasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminListasRoute: AdminListasRoute,
  ProcessoIdRoute: ProcessoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
